package krypton.runtime;

import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Consumer;

public final class KryptonRuntime {
    public static final String VERSION = "0.1.0";
    private static volatile KryptonRuntime INSTANCE;

    private final AtomicInteger actorCount = new AtomicInteger(0);
    private final ReentrantLock awaitLock = new ReentrantLock();
    private final Condition allDone = awaitLock.newCondition();
    private final Set<ActorThread> actors = ConcurrentHashMap.newKeySet();
    private volatile boolean shutdownRequested = false;

    public KryptonRuntime() {}

    public static void boot() {
        INSTANCE = new KryptonRuntime();
    }

    public static KryptonRuntime instance() {
        return INSTANCE;
    }

    /** Static entry point for generated bytecode ({@code invokestatic awaitAll}). */
    public static void awaitAllActors() {
        INSTANCE.awaitAll();
    }

    public <M> Ref<M> spawn(Consumer<Mailbox<M>> actorFn) {
        Mailbox<M> mailbox = new Mailbox<>();
        new ActorThread(() -> actorFn.accept(mailbox), mailbox, this);
        return mailbox.ref();
    }

    public <M> Ref<M> spawn(Mailbox<M> mailbox, Runnable body) {
        new ActorThread(body, mailbox, this);
        return mailbox.ref();
    }

    public void awaitAll() {
        awaitLock.lock();
        try {
            while (actorCount.get() > 0) {
                allDone.await();
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } finally {
            awaitLock.unlock();
        }
    }

    public void shutdown() {
        shutdownRequested = true;
        for (ActorThread actor : actors) {
            actor.thread().interrupt();
        }
    }

    public int actorCount() {
        return actorCount.get();
    }

    void trackActor(ActorThread actor) {
        actors.add(actor);
        actorCount.incrementAndGet();
    }

    void notifyActorDone(ActorThread actor) {
        actors.remove(actor);
        int remaining = actorCount.decrementAndGet();
        if (remaining == 0) {
            awaitLock.lock();
            try {
                allDone.signalAll();
            } finally {
                awaitLock.unlock();
            }
        }
    }
}
