//! Synthesize the `Kr$TestHarness` class for `krypton test`.
//!
//! The harness is a single class with a `public static void main(String[])`
//! method that boots the actor runtime, then for each discovered `test_*`
//! function hands a `(class, method, qualified-name, column-width)` tuple to
//! `KryptonTestSupport.runOneTest`. Per-test timeouts, exception capture,
//! formatting, and pass/fail bookkeeping all live in the Java helper, so the
//! generated bytecode is a flat sequence of `Invokestatic` calls with no
//! branches and no exception table — the JVM verifier needs no
//! `StackMapTable` frames for it.
//!
//! The harness is built directly against `ristretto_classfile` primitives —
//! it does not use the per-module `Compiler`/`BytecodeBuilder` because it has
//! no Krypton functions of its own.

use ristretto_classfile::attributes::{Attribute, Instruction};
use ristretto_classfile::{ClassAccessFlags, ClassFile, ConstantPool, Method, MethodAccessFlags};

use super::compiler::CodegenError;
use super::JAVA_21;

/// One discovered `test_*` function, ordered by the caller in the sequence the
/// harness should invoke them. `class_name` is the JVM-internal name of the
/// class that owns the static method; the harness emits this as a string
/// constant and resolves the method reflectively at runtime through
/// `KryptonTestSupport.runTestWithTimeout`, so no JVM descriptor is needed
/// in the constant pool.
#[derive(Debug, Clone)]
pub struct TestHarnessEntry {
    pub class_name: String,
    pub method_name: String,
    pub qualified_name: String,
}

/// JVM-internal name of the synthetic harness class.
pub const HARNESS_CLASS_NAME: &str = "Kr$TestHarness";

/// Build the `Kr$TestHarness` class file bytes.
pub fn generate_test_harness(entries: &[TestHarnessEntry]) -> Result<Vec<u8>, CodegenError> {
    let mut cp = ConstantPool::default();

    let this_class = cp.add_class(HARNESS_CLASS_NAME)?;
    let object_class = cp.add_class("java/lang/Object")?;
    let object_init = cp.add_method_ref(object_class, "<init>", "()V")?;

    let code_utf8 = cp.add_utf8("Code")?;
    let init_name = cp.add_utf8("<init>")?;
    let init_desc = cp.add_utf8("()V")?;
    let main_name = cp.add_utf8("main")?;
    let main_desc = cp.add_utf8("([Ljava/lang/String;)V")?;

    let runtime_class = cp.add_class("krypton/runtime/KryptonRuntime")?;
    let boot_ref = cp.add_method_ref(runtime_class, "boot", "()V")?;
    let await_ref = cp.add_method_ref(runtime_class, "awaitAllActors", "()V")?;

    let system_class = cp.add_class("java/lang/System")?;
    let exit_ref = cp.add_method_ref(system_class, "exit", "(I)V")?;

    let test_support_class = cp.add_class("krypton/runtime/KryptonTestSupport")?;
    let record_suite_start_ref =
        cp.add_method_ref(test_support_class, "recordSuiteStart", "()V")?;
    let run_one_test_ref = cp.add_method_ref(
        test_support_class,
        "runOneTest",
        "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V",
    )?;
    let print_summary_ref = cp.add_method_ref(test_support_class, "printSummary", "()V")?;
    let exit_code_ref =
        cp.add_method_ref(test_support_class, "exitCodeFromCounters", "()I")?;

    // Width of the qualified-name column in characters. The Java side uses
    // this with a `%-Ns` printf format so the elapsed-time column lines up
    // across the suite. Empty suites pass 0 — the value is never read because
    // no per-test calls are emitted.
    let column_width = column_width_for(entries);

    // Default constructor.
    let constructor = Method {
        access_flags: MethodAccessFlags::PUBLIC,
        name_index: init_name,
        descriptor_index: init_desc,
        attributes: vec![Attribute::Code {
            name_index: code_utf8,
            max_stack: 1,
            max_locals: 1,
            code: vec![
                Instruction::Aload_0,
                Instruction::Invokespecial(object_init),
                Instruction::Return,
            ],
            exception_table: vec![],
            attributes: vec![],
        }],
    };

    // ----- main body -----
    //
    // Boot the runtime, record suite start, dispatch each test by name,
    // print the summary, await pending actors, then exit with the harness's
    // computed status code. The body is straight-line — no branches, no
    // try/catch — so no StackMapTable frames are required.
    let mut code: Vec<Instruction> = Vec::new();
    code.push(Instruction::Invokestatic(boot_ref));
    code.push(Instruction::Invokestatic(record_suite_start_ref));

    for entry in entries {
        let class_name_idx = cp.add_string(entry.class_name.clone())?;
        let method_name_idx = cp.add_string(entry.method_name.clone())?;
        let qualified_name_idx = cp.add_string(entry.qualified_name.clone())?;
        push_ldc_string(&mut code, class_name_idx);
        push_ldc_string(&mut code, method_name_idx);
        push_ldc_string(&mut code, qualified_name_idx);
        push_int_const(&mut code, column_width);
        code.push(Instruction::Invokestatic(run_one_test_ref));
    }

    code.push(Instruction::Invokestatic(print_summary_ref));
    code.push(Instruction::Invokestatic(await_ref));
    code.push(Instruction::Invokestatic(exit_code_ref));
    code.push(Instruction::Invokestatic(exit_ref));
    code.push(Instruction::Return);

    // Largest stack reach: three string refs plus the int column-width
    // operand, all four pushed before `runOneTest`'s invokestatic.
    let max_stack: u16 = 4;
    // Slot 0 is the `String[] args` parameter; nothing else is stored.
    let max_locals: u16 = 1;

    let main_method = Method {
        access_flags: MethodAccessFlags::PUBLIC | MethodAccessFlags::STATIC,
        name_index: main_name,
        descriptor_index: main_desc,
        attributes: vec![Attribute::Code {
            name_index: code_utf8,
            max_stack,
            max_locals,
            code,
            exception_table: vec![],
            attributes: vec![],
        }],
    };

    let class_file = ClassFile {
        version: JAVA_21,
        access_flags: ClassAccessFlags::PUBLIC | ClassAccessFlags::SUPER,
        constant_pool: cp,
        this_class,
        super_class: object_class,
        methods: vec![constructor, main_method],
        ..Default::default()
    };

    let mut buffer = Vec::new();
    class_file.to_bytes(&mut buffer)?;
    Ok(buffer)
}

/// Char-count of the longest qualified-name across the suite (or 0 for an
/// empty suite). The Java printf format string composed on this value pads
/// every name to the same column so the elapsed-time column aligns.
fn column_width_for(entries: &[TestHarnessEntry]) -> i16 {
    let max_chars = entries
        .iter()
        .map(|e| e.qualified_name.chars().count())
        .max()
        .unwrap_or(0);
    // A qualified name longer than i16::MAX (32 767) cannot be represented
    // by Bipush/Sipush. Practical names are well under any conceivable
    // limit; if this ever fires it indicates corrupt upstream data, not a
    // real test name. Fail hard rather than silently truncate.
    assert!(
        max_chars <= i16::MAX as usize,
        "ICE: qualified test name longer than {} characters",
        i16::MAX
    );
    max_chars as i16
}

fn push_ldc_string(code: &mut Vec<Instruction>, idx: u16) {
    if idx <= 255 {
        code.push(Instruction::Ldc(idx as u8));
    } else {
        code.push(Instruction::Ldc_w(idx));
    }
}

/// Push a positive int constant in the smallest available encoding.
/// `iconst_<n>` for 0..=5, `bipush` for ≤127, `sipush` otherwise. The
/// caller has already asserted the value fits in i16.
fn push_int_const(code: &mut Vec<Instruction>, value: i16) {
    match value {
        0 => code.push(Instruction::Iconst_0),
        1 => code.push(Instruction::Iconst_1),
        2 => code.push(Instruction::Iconst_2),
        3 => code.push(Instruction::Iconst_3),
        4 => code.push(Instruction::Iconst_4),
        5 => code.push(Instruction::Iconst_5),
        v if (i8::MIN as i16..=i8::MAX as i16).contains(&v) => {
            code.push(Instruction::Bipush(v as i8));
        }
        v => code.push(Instruction::Sipush(v)),
    }
}
